Memoir/urls.py
from __future__ import unicode_literals
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.views.generic import TemplateView
from django.views.i18n import JavaScriptCatalog
from .views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    url(r'^$', index, name = 'index'),
    url(r'^about$', TemplateView.as_view(template_name='about.html'), name = 'about'),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^login$', auth_views.login, {'template_name': 'profiles/login.html', }, name = 'login'),
    url(r'^switch_user$', auth_views.logout_then_login, name = 'switch-user'),
    url(r'^user/', include('profiles.urls')),
    url(r'^(?P<board>\w+)/', include('quotes.urls', namespace = 'board')),
    prefix_default_language = False,
)

quotes/urls.py
from __future__ import unicode_literals
from django.conf.urls import url, include
from .views import QuoteList, QuoteDetail, QuoteCreate, QuoteEdit, QuoteDelete
from .views import TopQuotes, LikeView, LikersList, Comments

quote_urlpatterns = [
    url(r'^create$', QuoteCreate.as_view(), name = 'create'),
    url(r'^(?P<pk>\d+)$', QuoteDetail.as_view(), name = 'detail'),
    url(r'^(?P<pk>\d+)/edit$', QuoteEdit.as_view(), name = 'edit'),
    url(r'^(?P<pk>\d+)/delete$', QuoteDelete.as_view(), name = 'delete'),
    url(r'^(?P<pk>\d+)/like$', LikeView.as_view(), name = 'like'),
    url(r'^(?P<pk>\d+)/likers$', LikersList.as_view(), name = 'likers'),
    url(r'^(?P<pk>\d+)/comment$', Comments.as_view(), name = 'comment-create'),
    url(r'^(?P<pk>\d+)/comment/(?P<comment_pk>\d+)$', Comments.as_view(), name = 'comment'),
]

urlpatterns = [
    url(r'^$', QuoteList.as_view(), name = 'list'),
    url(r'^top$', TopQuotes.as_view(), name = 'top'),
    url(r'^quote/', include(quote_urlpatterns, namespace = 'quote')),
]

quotes/models.py
from __future__ import unicode_literals
from django.utils.translation import pgettext_lazy
from django.utils.encoding import python_2_unicode_compatible
from django.utils.deconstruct import deconstructible
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from django.core.urlresolvers import reverse
from django.core.exceptions import ValidationError
from django.db.models import Model
from django.db.models import DateTimeField, ForeignKey, CharField, TextField, SlugField, ManyToManyField
from .regex import REGEX_SPEAKER, REGEX_REFERENCE

@deconstructible
class WordCountValidator(object):
    def __init__(self, min_count = 0, max_count = None):
        if max_count is not None and max_count < min_count:
            raise ValueError('min_count must be less than max_count')

        self.min_count = min_count
        self.max_count = max_count

    def __call__(self, value):
        word_count = sum(len(line.split(' ')) for line in value.splitlines())

        if word_count < self.min_count:
            raise ValidationError('Enter at least %d words' % (self.min_count, ))

        if self.max_count and self.max_count < word_count:
            raise ValidationError('Can\'t enter more than %d words' % (self.max_count, ))

@python_2_unicode_compatible
class Board(Model):
    slug = SlugField(max_length = 20, unique = True)
    name = CharField(max_length = 20, unique = True)
    groups = ManyToManyField(Group, related_name = 'boards')

    def __str__(self):
        return '%s' % (self.name, )

@python_2_unicode_compatible
class Quote(Model):
    created = DateTimeField(auto_now_add = True)
    last_modified = DateTimeField(auto_now = True)
    board = ForeignKey(Board, related_name = 'quotes')
    author = ForeignKey(settings.AUTH_USER_MODEL, related_name = 'author_of')
    title = CharField(
        max_length = 120,
        blank = True,
        verbose_name = pgettext_lazy('Quote', 'title'))
    text = TextField(
        validators = [WordCountValidator(min_count = 2), ],
        verbose_name = pgettext_lazy('Quote', 'text'))
    mentions = ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank = True,
        editable = False,
        related_name = 'mentioned_in')
    likers = ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank = True,
        editable = False,
        related_name = 'likes')

    def __str__(self):
        if self.title:
            return self.title
        if self.id:
            return '#%d' % (self.id, )
        return 'Quote object'

    def save(self, *args, **kws):
        super(Quote, self).save(*args, **kws)
        self.__update_mentions()

    def get_absolute_url(self):
        return reverse('board:quote:detail', kwargs = {'board': self.board.slug, 'pk': self.pk, })

    def __update_mentions(self):
        self.mentions.clear()

        # Mark speakers as mentioned.
        for (speaker, _, _) in REGEX_SPEAKER.findall(self.text):
            try:
                self.mentions.add(get_user_model().objects.get(username = speaker))
            except get_user_model().DoesNotExist:
                # TODO: Log warning somewhere.
                pass

        # Mark referenced users as mentioned.
        for (_, reference, _) in REGEX_REFERENCE.findall(self.text):
            try:
                self.mentions.add(get_user_model().objects.get(username = reference))
            except get_user_model().DoesNotExist:
                # TODO: Log warning somewhere.
                pass

    class Meta:
        ordering = ('-created', )

@python_2_unicode_compatible
class Comment(Model):
    created = DateTimeField(auto_now_add = True)
    last_modified = DateTimeField(auto_now = True)
    author = ForeignKey(settings.AUTH_USER_MODEL, related_name = 'comments')
    quote = ForeignKey(Quote, related_name = 'comments')
    text = TextField(verbose_name = pgettext_lazy('Comment', 'text'))

    def __str__(self):
        return '#%d/%d' % (self.quote.id, self.id, )

quotes/views.py
from __future__ import unicode_literals
from httplib import NO_CONTENT, BAD_REQUEST
from django.conf import settings
from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse
from django.db.models import Count
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.http import HttpResponse, JsonResponse, Http404, QueryDict
from django.http import HttpResponseForbidden
from .models import Board, Quote, Comment

try:
    QUOTE_LIST_PAGINATION = settings.QUOTE_LIST_PAGINATION
except AttributeError:
    QUOTE_LIST_PAGINATION = 25

class BoardViewMixin(object):
    @property
    def board(self):
        return Board.objects.get(slug__iexact = self.kwargs.get('board', ''))

    def _get_quote_or_404(self, quote_pk):
        return get_object_or_404(
            self.board.quotes.all(),
            pk = quote_pk)

    def _get_comment_or_404(self, quote_pk, comment_pk):
        return get_object_or_404(
            self._get_quote_or_404(quote_pk).comments.all(),
            pk = comment_pk)

class QuoteList(ListView, BoardViewMixin):
    model = Quote
    template_name = 'quotes/list.html'
    context_object_name = 'quotes'
    paginate_by = QUOTE_LIST_PAGINATION

    def get_queryset(self):
        queryset = super(QuoteList, self).get_queryset() \
            .filter(board__slug__iexact = self.board.slug)

        author = self.request.GET.get('by', None)
        mentions = self.request.GET.get('mentioned', None)

        # Filter by author.
        if author is not None:
            queryset = queryset.filter(author__username__exact = author)

        # Filter by mentioned user.
        if mentions is not None:
            # Split mentioned list and remove any empty items.
            mentions = set(mentions.split(',')) - set([''])
            queryset = queryset.filter(mentions__username__in = mentions).distinct()

        return queryset

@method_decorator(login_required, name = 'dispatch')
class QuoteCreate(CreateView, BoardViewMixin):
    model = Quote
    template_name = 'quotes/create.html'
    fields = ('title', 'text', )

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.board = self.board
        return super(QuoteCreate, self).form_valid(form)

class QuoteDetail(DetailView, BoardViewMixin):
    model = Quote
    template_name = 'quotes/detail.html'
    context_object_name = 'quote'

@method_decorator(login_required, name = 'dispatch')
class QuoteEdit(UpdateView, BoardViewMixin):
    model = Quote
    template_name = 'quotes/edit.html'
    fields = ('title', 'text', )

@method_decorator(login_required, name = 'dispatch')
class QuoteDelete(DeleteView, BoardViewMixin):
    model = Quote

    def get_success_url(self):
        return reverse('board:list', kwargs = {'board': self.board.slug, })

class TopQuotes(QuoteList, BoardViewMixin):
    def get_queryset(self):
        queryset = super(TopQuotes, self).get_queryset().annotate(likers_count = Count('likers'))
        return queryset.filter(likers_count__gte = 1).order_by('-likers_count', '-created')

    def get_context_data(self, **kwargs):
        try:
            return super(TopQuotes, self).get_context_data(**kwargs)
        except Http404:
            # If the user un-liked a quote, the pagination might get screwed up
            # trying to move to the next page. In this case, we reset the page
            # number to 1.
            self.kwargs['page'] = 1
            return super(TopQuotes, self).get_context_data(**kwargs)

class LikeView(View, BoardViewMixin):
    def get(self, request, board, pk):
        quote = self._get_quote_or_404(pk)
        return JsonResponse({'likers': map(str, quote.likers.all()), })

    def put(self, request, board, pk):
        if self.request.user.pk is None:
            return HttpResponseForbidden()

        quote = self._get_quote_or_404(pk)
        quote.likers.add(self.request.user)
        return JsonResponse({'likers': map(str, quote.likers.all()), })

    def delete(self, request, board, pk):
        if self.request.user.pk is None:
            return HttpResponseForbidden()

        quote = self._get_quote_or_404(pk)
        quote.likers.remove(self.request.user)
        return JsonResponse({'likers': map(str, quote.likers.all()), })

class LikersList(TemplateView, BoardViewMixin):
    template_name = 'quotes/likers.html'

    def get_context_data(self, **kwargs):
        context = super(LikersList, self).get_context_data(**kwargs)
        likers = self.request.GET.getlist('likers[]')
        likers = get_user_model().objects.filter(username__in = likers)

        if self.request.user in likers:
            context['liked_by_user'] = True
            context['likers'] = likers.exclude(id = self.request.user.id)
        else:
            context['likers'] = likers

        return context

@method_decorator(login_required, name = 'dispatch')
class Comments(View, BoardViewMixin):
    def post(self, request, board, pk):
        comment_text = self.request.POST['text']

        # It's worth noting we check the stripped version, but save the text as
        # it was given.
        if not comment_text.strip():
            return HttpResponse(status = BAD_REQUEST)

        quote = self._get_quote_or_404(pk)
        comment = quote.comments.create(
            author = self.request.user,
            text = comment_text)

        return JsonResponse({'comment_pk': comment.pk, })

    def put(self, request, board, pk, comment_pk):
        comment = self._get_comment_or_404(pk, comment_pk)
        comment_text = QueryDict(request.body)['text']

        # It's worth noting we check the stripped version, but save the text as
        # it was given.
        if not comment_text.strip():
            return HttpResponse(status = BAD_REQUEST)

        comment.text = comment_text
        comment.save()

        return HttpResponse(status = NO_CONTENT)

    def delete(self, request, board, pk, comment_pk):
        comment = self._get_comment_or_404(pk, comment_pk)
        comment.delete()

        return HttpResponse(status = NO_CONTENT)

templates/about.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "About Memoir" %}{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="jumbotron">
          <h1>{% trans "About Memoir" %}</h1>
          <p>
          {% spaceless %}
            {% trans "This is a quotes server made with &lt;3 by Niv Ben-David." %}<br/>
            {% trans "For any issues, remarks, suggestions or otherwise, please see:" %}
            <a href="http://github.com/nivbend/memoir">github.com/nivbend/memoir</a>
          {% endspaceless %}
          </p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/base.html
{% load staticfiles %}
{% load i18n %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}" rtl="{{ LANGUAGE_CODE|language_bidi|yesno:"rtl,ltr" }}">
  <head>
    <title>{% block title %}{% endblock %}</title>
    {% block stylesheets %}
      <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
      <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
      {% if LANGUAGE_CODE|language_bidi %}
        <link rel="stylesheet" href="{% static 'css/bootstrap-rtl.min.css' %}">
      {% endif %}
    {% endblock %}
  </head>

  <body>
    {% include 'navbar.html' %}
    {% block content %}{% endblock %}
    {% block scripts %}
      <script type="text/javascript" src="{% static 'js/jquery-2.2.4.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
      <script type="text/javascript" src="{% static 'js/jquery.textcomplete.min.js' %}"></script>
      <script type="text/javascript" src="{% url 'javascript-catalog' %}"></script>
      <script type="text/javascript">
        $("textarea").textcomplete([
          { // References strategy.
            match: /(^|\s)@([-\s\w\u0590-\u05fe]+)$/u,
            indexNumber: 2,
            search: function (term, callback) {
              $.getJSON("{% url 'user-search' %}", { q: term })
                .done(function (response) { callback(response.matches); })
                .fail(function ()         { callback([]);   });
            },
            template: function (user, term) {
              display = user.full_name;
              words = term.split(" ")
              for (i = 0; i < words.length; ++i) {
                if (!words[i]) {
                  continue;
                }
                display = display.split(words[i]).join("<strong>" + words[i] + "</strong>");
              }
              return display;
            },
            replace: function (user) {
              return "$1@" + user.username;
            },
            cache: true
          },
          { // Speakers strategy.
            match: /(^)([-\s\w\u0590-\u05fe]+)$/um,
            indexNumber: 2,
            search: function (term, callback) {
              $.getJSON("{% url 'user-search' %}", { q: term })
                .done(function (response) { callback(response.matches); })
                .fail(function ()         { callback([]);   });
            },
            template: function (user, term) {
              display = user.full_name;
              words = term.split(" ")
              for (i = 0; i < words.length; ++i) {
                if (!words[i]) {
                  continue;
                }
                display = display.split(words[i]).join("<strong>" + words[i] + "</strong>");
              }
              return display;
            },
            replace: function (user) {
              return user.username + ": ";
            },
            cache: true
          }
        ]);
      </script>
    {% endblock %}
  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}Memoir{% endblock %}

{% block content %}
  {% url 'admin:quotes_board_add' as add_url %}
  <div class="container">
    <div class="row">
      {% if boards %}
        <div class="col-md-6 col-md-offset-3">
          <div class="list-group">
            {% for board in boards %}
              <a href="{% url 'board:list' board=board.slug %}" class="list-group-item">
                {{ board.name }}
                <span class="badge">{{ board.quotes.count }}</span>
              </a>
            {% endfor %}
          </div>
        </div>
      {% else %}
        <div class="col-md-12">
          <div class="jumbotron">
            <h1>{% trans "No boards, apparently" %}</h1>
          </div>
        </div>
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/navbar.html
{% load i18n %}
{% load profiles %}

{% url 'board:list' board=view.kwargs.board as recent_page %}
{% url 'board:top' board=view.kwargs.board as top_page %}
{% url 'board:quote:create' board=view.kwargs.board as create_page %}

<div class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'index' %}">Memoir</a>
    </div>
    <div class="navbar-collapse collapse">
      {% if view.kwargs.board is not None %}
        <ul class="nav navbar-nav">
          <span class="navbar-text">{{ view.board.name }}</span>
          <li class="{% if request.path == recent_page %}active{% endif %}">
            <a href="{{ recent_page }}">{% trans "Recent" %}</a>
          </li>
          <li class="{% if request.path == top_page %}active{% endif %}">
            <a href="{{ top_page }}">{% trans "Top" %}</a>
          </li>
        </ul>
      {% endif %}
      <ul class="nav navbar-nav navbar-right flip">
        {% if view.kwargs.board is not None %}
          <li>
            <div class="btn-nav">
              <a class="btn btn-primary navbar-btn" href="{{ create_page }}">{% trans "Create" %}</a>
            </div>
          </li>
        {% endif %}
        <li>
          <div class="navbar-text">
            {% if user.is_authenticated %}
              <span>
                {% trans "Logged in as " %}<strong>{% profile_link user classes="navbar-link" %}</strong>
              </span>
              <span>
                (<a class="navbar-link" href="{% url 'switch-user' %}">{% trans "switch" %}</a>)
              </span>
            {% else %}
              <a class="navbar-link" href="{% url 'login' %}">{% trans "Login" %}</a>
            {% endif %}
          </div>
        </li>
        <li>
          <div class="navbar-text">
            <a class="navbar-link" href="{% url 'about' %}">{% trans "About Memoir" %}</a>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>

templates/quote_view.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}{{ quote }}{% endblock %}

{% block stylesheets %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static 'css/vertical_align.css' %}">
{% endblock %}

{% block scripts %}
  {{ block.super }}
  <script type="text/javascript" src="{% static 'js/csrf.js' %}"></script>
  <script type="text/javascript" src="{% static 'quotes/js/likes.js' %}"></script>
  <script type="text/javascript" src="{% static 'quotes/js/comments.js' %}"></script>
{% endblock %}

templates/single_quote.html
{% load i18n %}
{% load profiles %}
{% load quotes %}
{% load likes %}

{% blocktrans asvar comment_count count counter=quote.comments.count %}
{{ counter }} comment
{% plural %}
{{ counter }} comments
{% endblocktrans %}

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading clearfix">
        {% if quote.author == user or user.is_superuser %}{% user_buttons %}{% endif %}
        <span class="panel-title">{% quote_title %}</span>
        <bdo>&nbsp;</bdo>
        <span class="label label-default">{{ comment_count }}</span>
      </div>
      <div class="panel-body">{% quote_body %}</div>
      <div class="panel-footer clearfix">
        <div class="row vertical-align">
          <div class="col-md-5">
            <span class="text-muted">
              {% spaceless %}
                <span>{% trans "By " %}<bdi>{% profile_link quote.author %}</bdi></span>
                {% if view.board is None %}
                  <span>&nbsp;{% trans "on " %}<bdi>
                      <a href="{% url 'board:top' board=quote.board.slug %}">{{ quote.board }}</a>
                  </bdi></span>
                {% endif %}
                <span>,&nbsp;{{ quote.created }}</span>
              {% endspaceless %}
            </span>
          </div>
          <div class="col-md-1 col-md-offset-6">
            <div class="btn-group pull-right flip" role="group">
              {% like_button %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% if quote.author == user or user.is_superuser %}
  {% delete_modal %}
{% endif %}